Add array doctrine type
assoconnect/validator-bundle pull request #23
Opened 2021-11-04 15:53 UTC by hammat

2021-11-04 17:19 UTC, TristanPouliquen requested changes

2021-11-04 17:19 UTC, TristanPouliquen commented on src/Validator/Constraints/EntityValidator.php
> +                break;
rajoute un `$constraints[] = new Type('array');` non ?

2021-11-04 17:44 UTC, hammat commented on src/Validator/Constraints/EntityValidator.php
> +                break;
@TristanPouliquen je croyais aussi mais il ne connaissais pas le type array. J'ai donc laissé vide comme pour json.

2021-11-05 08:38 UTC, TristanPouliquen commented on src/Validator/Constraints/EntityValidator.php
> +                break;
https://symfony.com/doc/current/reference/constraints/Type.html

La string 'array' est normalement une valeur acceptée. Derrière, Type utilisera alors `is_array()`

2021-11-05 08:42 UTC, hammat commented on src/Validator/Constraints/EntityValidator.php
> +                break;
Oh, je regarde à nouveau, merci !

2021-11-05 15:23 UTC, merged